
USE 4064_4078_4284;

INSERT INTO CATEGORIE (nom) VALUES
('Français'),
('Italien'),
('Japonais'),
('Mexicain'),
('Indien'),
('Thaïlandais'),
('Américain'),
('Oriental'),
('Maghrébin'),
('Hawaïen'),
('Dessert');

INSERT INTO plats (name, description, image_url, note, emoji, temps, categorie_id, calorie) VALUES
('Ramen Tonkotsu', 'Bouillon de porc riche, nouilles fraîches, œuf mollet et chashu.', 'images/ramen.jpg', 5, '🍜', 45, (SELECT id FROM CATEGORIE WHERE nom = 'Japonais'), 620),
('Pizza Margherita', 'Tomate San Marzano, mozzarella di bufala, basilic frais.', 'images/pizza.jpg', 5, '🍕', 30, (SELECT id FROM CATEGORIE WHERE nom = 'Italien'), 540),
('Tacos al Pastor', 'Porc mariné aux épices, ananas, coriandre et salsa verde.', 'images/tacos.jpg', 5, '🌮', 20, (SELECT id FROM CATEGORIE WHERE nom = 'Mexicain'), 480),
('Pad Thaï', 'Nouilles de riz sautées, crevettes, cacahuètes et citron vert.', 'images/padthai.jpg', 5, '🍝', 25, (SELECT id FROM CATEGORIE WHERE nom = 'Thaïlandais'), 550),
('Burger Smash', 'Double galette beurrée, cheddar fondu, pickles maison.', 'images/burger.jpg', 5, '🍔', 15, (SELECT id FROM CATEGORIE WHERE nom = 'Américain'), 750),
('Sushi Omakase', 'Sélection du chef : thon, saumon, oursin et bar de ligne.', 'images/sushi.jpg', 5, '🍣', 60, (SELECT id FROM CATEGORIE WHERE nom = 'Japonais'), 420),
('Shakshuka', 'Œufs pochés dans une sauce tomate épicée aux poivrons.', 'images/shakshuka.jpg', 4, '🍳', 20, (SELECT id FROM CATEGORIE WHERE nom = 'Oriental'), 390),
('Crêpe Suzette', 'Crêpes au beurre d''agrumes flambées au Grand Marnier.', 'images/crepes.jpg', 5, '🥞', 15, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 310),
('Biryani d''agneau', 'Riz basmati parfumé, agneau tendre, safran et raïta.', 'images/biryani.jpg', 5, '🍚', 90, (SELECT id FROM CATEGORIE WHERE nom = 'Indien'), 680),
('Poke Bowl Saumon', 'Riz sushi, saumon frais, avocat, edamame et sauce ponzu.', 'images/pokebowl.jpg', 5, '🥗', 10, (SELECT id FROM CATEGORIE WHERE nom = 'Hawaïen'), 490),
('Couscous Royal', 'Semoule fine, merguez, poulet, légumes et bouillon parfumé.', 'images/couscous.jpg', 5, '🍲', 75, (SELECT id FROM CATEGORIE WHERE nom = 'Maghrébin'), 720),
('Tiramisu', 'Mascarpone aérien, biscuits imbibés d''espresso et cacao.', 'images/tiramisu.jpg', 5, '🍮', 20, (SELECT id FROM CATEGORIE WHERE nom = 'Dessert'), 380),
('Bœuf Bourguignon', 'Bœuf mijoté au vin rouge, champignons et lardons.', 'images/boeuf.jpg', 5, '🍲', 180, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 650),
('Coq au Vin', 'Coq cuit au vin rouge, champignons et oignons grelots.', 'images/coq.jpg', 4, '🍗', 150, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 580),
('Ratatouille', 'Mijoté de légumes provençaux : aubergines, courgettes, poivrons.', 'images/ratatouille.jpg', 4, '🥘', 45, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 210),
('Cassoulet', 'Haricots blancs mijotés avec confit de canard et saucisse.', 'images/cassoulet.jpg', 5, '🍲', 240, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 890),
('Quiche Lorraine', 'Tarte salée à la pâte brisée, œufs, lardons et crème.', 'images/quiche.jpg', 4, '🥧', 50, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 480),
('Soupe à l''Oignon', 'Soupe gratinée à l''oignon caramélisé et comté.', 'images/soupe.jpg', 4, '🥣', 60, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 350),
('Croissant', 'Viennoiserie feuilletée au beurre.', 'images/croissant.jpg', 5, '🥐', 20, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 250),
('Macaron', 'Petit gâteau à base de poudre d''amande.', 'images/macaron.jpg', 5, '🍪', 15, (SELECT id FROM CATEGORIE WHERE nom = 'Français'), 120),
('Spaghetti Carbonara', 'Pâtes à la crème, œufs, guanciale et pecorino.', 'images/carbonara.jpg', 5, '🍝', 20, (SELECT id FROM CATEGORIE WHERE nom = 'Italien'), 680),
('Lasagne', 'Pâtes alternées avec sauce bolognaise, béchamel et parmesan.', 'images/lasagne.jpg', 5, '🍝', 60, (SELECT id FROM CATEGORIE WHERE nom = 'Italien'), 720),
('Risotto aux Champignons', 'Riz crémeux aux champignons et parmesan.', 'images/risotto.jpg', 4, '🍚', 35, (SELECT id FROM CATEGORIE WHERE nom = 'Italien'), 490),
('Gelato', 'Glace artisanale italienne.', 'images/gelato.jpg', 5, '🍦', 5, (SELECT id FROM CATEGORIE WHERE nom = 'Dessert'), 180),
('Tempura', 'Beignets de crevettes et légumes frits.', 'images/tempura.jpg', 4, '🍤', 25, (SELECT id FROM CATEGORIE WHERE nom = 'Japonais'), 380),
('Okonomiyaki', 'Galette salée japonaise garnie (chou, porc, sauce okonomiyaki).', 'images/okonomiyaki.jpg', 4, '🥞', 30, (SELECT id FROM CATEGORIE WHERE nom = 'Japonais'), 450),
('Miso Soup', 'Soupe traditionnelle au miso, tofu et algues.', 'images/miso.jpg', 4, '🥣', 10, (SELECT id FROM CATEGORIE WHERE nom = 'Japonais'), 70),
('Gyozas', 'Raviolis japonais grillés à la poêle.', 'images/gyozas.jpg', 5, '🥟', 20, (SELECT id FROM CATEGORIE WHERE nom = 'Japonais'), 320),
('Guacamole', 'Purée d''avocat, coriandre, oignon, tomate et citron vert.', 'images/guacamole.jpg', 5, '🥑', 10, (SELECT id FROM CATEGORIE WHERE nom = 'Mexicain'), 280),
('Tamales', 'Masa de maïs farcie aux viandes ou fromage.', 'images/tamales.jpg', 4, '🫔', 80, (SELECT id FROM CATEGORIE WHERE nom = 'Mexicain'), 450),
('Chicken Tikka Masala', 'Poulet mariné grillé en sauce crémeuse aux épices.', 'images/tikka.jpg', 5, '🍛', 50, (SELECT id FROM CATEGORIE WHERE nom = 'Indien'), 620),
('Naan', 'Pain indien cuit au four tandoori.', 'images/naan.jpg', 5, '🫓', 15, (SELECT id FROM CATEGORIE WHERE nom = 'Indien'), 220),
('Tom Yam Goong', 'Soupe aigre-douce aux crevettes et citronnelle.', 'images/tomyam.jpg', 5, '🥣', 25, (SELECT id FROM CATEGORIE WHERE nom = 'Thaïlandais'), 280),
('Massaman Curry', 'Curry doux à la viande, pommes de terre et cacahuètes.', 'images/massaman.jpg', 5, '🍛', 60, (SELECT id FROM CATEGORIE WHERE nom = 'Thaïlandais'), 590),
('Spring Rolls', 'Rouleaux de printemps aux légumes frais.', 'images/springrolls.jpg', 4, '🥬', 15, (SELECT id FROM CATEGORIE WHERE nom = 'Thaïlandais'), 180),
('BBQ Ribs', 'Côtes de porc laquées à la sauce barbecue.', 'images/ribs.jpg', 5, '🍖', 120, (SELECT id FROM CATEGORIE WHERE nom = 'Américain'), 890),
('Mac & Cheese', 'Pâtes à la sauce cheddar intense.', 'images/macncheese.jpg', 4, '🧀', 25, (SELECT id FROM CATEGORIE WHERE nom = 'Américain'), 580),
('Falafel', 'Boulettes de pois chiches frites.', 'images/falafel.jpg', 4, '🧆', 20, (SELECT id FROM CATEGORIE WHERE nom = 'Oriental'), 340),
('Hummus', 'Purée de pois chiches au tahini, citron et ail.', 'images/hummus.jpg', 5, '🥙', 10, (SELECT id FROM CATEGORIE WHERE nom = 'Oriental'), 290),
('Pastilla', 'Feuilleté sucré-salé au pigeon ou poulet, amandes et cannelle.', 'images/pastilla.jpg', 5, '🥮', 90, (SELECT id FROM CATEGORIE WHERE nom = 'Maghrébin'), 620),
('Tajine', 'Mijoté berbère à la viande, fruits secs et légumes.', 'images/tajine.jpg', 5, '🍲', 120, (SELECT id FROM CATEGORIE WHERE nom = 'Maghrébin'), 540),
('Poke Bowl Thon', 'Riz sushi, thon frais, mangue, avocat et graines de sésame.', 'images/pokethon.jpg', 5, '🐟', 15, (SELECT id FROM CATEGORIE WHERE nom = 'Hawaïen'), 460),
('Mochi', 'Pâte de riz gluant fourrée à la pâte de haricot rouge.', 'images/mochi.jpg', 5, '🍡', 10, (SELECT id FROM CATEGORIE WHERE nom = 'Dessert'), 180),
('Cheesecake', 'Gâteau crémeux au fromage frais.', 'images/cheesecake.jpg', 5, '🍰', 60, (SELECT id FROM CATEGORIE WHERE nom = 'Dessert'), 410),
('Brownie', 'Gâteau au chocolat dense.', 'images/brownie.jpg', 5, '🍫', 30, (SELECT id FROM CATEGORIE WHERE nom = 'Dessert'), 390);

INSERT INTO users (username, password) VALUES
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'); 